//list of POSTS
const REQUEST_POSTS = "REQUEST_POSTS";
const RECEIVE_POSTS = "RECEIVE_POSTS";
const FAILURE_POSTS = "FAILURE_POSTS";

//POST by id

const REQUEST_POST = "REQUEST_POST";
const RECEIVE_POST = "RECEIVE_POST";
const FAILURE_POST = "FAILURE_POST";

const UPDATE_POST_DATA = "UPDATE_POST_DATA";
const CLEAR_POST_DATA = "CLEAR_POST_DATA";

const CREATE_POST = "CREATE_POST";

export {
  RECEIVE_POSTS,
  REQUEST_POSTS,
  FAILURE_POSTS,
  RECEIVE_POST,
  REQUEST_POST,
  FAILURE_POST,
  UPDATE_POST_DATA,
  CLEAR_POST_DATA,
  CREATE_POST
};
