//list of users
const REQUEST_USERS = "REQUEST_USERS";
const RECEIVE_USERS = "RECEIVE_USERS";
const FAILURE_USERS = "FAILURE_USERS";

//user by id

const REQUEST_USER = "REQUEST_USER";
const RECEIVE_USER = "RECEIVE_USER";
const FAILURE_USER = "FAILURE_USER";

const UPDATE_USER_DATA = "UPDATE_USER_DATA";
const CLEAR_USER_DATA = "CLEAR_USER_DATA";

export {
  RECEIVE_USERS,
  REQUEST_USERS,
  FAILURE_USERS,
  RECEIVE_USER,
  REQUEST_USER,
  FAILURE_USER,
  UPDATE_USER_DATA,
  CLEAR_USER_DATA
};
