version: 2.1

orbs:
  python: circleci/python@0.2.1
  win: circleci/windows@2.2.0

jobs:
  #Linting and unit test
  unittest:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name : Run Unit Tests
          command: |
            python3 -m unittest tests/test_linting.py
            flake8 --max-line-length=120 --ignore=PT009

  #UNIX integration 
  integration-on-UNIX:
    executor: python/default
    environment:
          POSTGRES_USER: biosustain
          POSTGRES_DB: IsaTAB_DB
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            sudo apt-get install postgresql
            sudo apt install -y postgresql-client || true
            pip install -r requirements.txt

      - run:
          name: Integrate IsaTAB.sql into the database
          command: |
            sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
            sudo -u postgres psql -c "CREATE DATABASE testdb;"
            sudo service postgresql start
            psql -f AutoFlow-OmicsDataHandling/IsaTab.sql testdb

  #Windows integration
  Integration-on-windows:
    executor:
      name: win/default
      shell: powershell.exe

    steps:
      - checkout
      - run:
          name: Install postgresql
          command : |
            choco install postgresql
            python -m pip install -U pip

      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt

      - run:
          name : Integrate IsaTAB.sql into the database
          command: |
            pg_ctl -D "C:\Program Files\PostgreSQL\9.6\data" start
            psql -f AutoFlow-OmicsDataHandling/IsaTab.sql IsaTAB_DB


workflows:
  main:
    jobs:
      - integration-on-UNIX
      - unittest
