version: 2.1

orbs:
  python: circleci/python@0.2.1
  win: circleci/windows@2.2.0

jobs:
  unittest:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name : Run Unit Tests
          command: |
            python3 -m unittest tests/test_linting.py
            flake8 --max-line-length=120 --ignore=PT009

  integration_UNIX:
    docker:

      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable

      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: biosustain
          POSTGRES_DB: Isatab_DB
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Integrate IsaTAB.sql into the database
          command: |
            sudo apt-get install postgresql-client
            psql Isatab_DB < AutoFlow-OmicsDataHandling/IsaTab.sql

  Integration-on-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Install postgresql
          command : |
            choco install postgresql
            python -m pip install -U pip
      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt
      - run:
          name : Integrate IsaTAB.sql into the database
          command: |
            choco install postgresql
            psql -h localhost -U biosustain -d biosustaindb -f AutoFlow-OmicsDataHandling/IsaTab.sql


workflows:
  main:
    jobs:
      - integration-on-windows
      - unittest
