version: 2.1

orbs:
  python: circleci/python@0.2.1
  win: circleci/windows@2.2.0

jobs:
  integration_UNIX:
    working_directory: ~/appName
    docker:
      - image: ruby:2.3.1-jessie
        environment:
          PG_HOST: localhost
          PG_USER: ubuntu
          RAILS_ENV: test
          RACK_ENV: test

      - image: postgres:9.6-jessie
        environment:
          POSTGRES_USER: biosustain
          POSTGRES_DB: db_IsaTab
    executor: python/default
    steps:
      - checkout
      - run:
          name: Set up db
          command: |

            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate

          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/db_IsaTab"
  
  unittest:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name : Run Unit Tests
          command: |
            python3 -m unittest tests/test_linting.py
            flake8 --max-line-length=120 --ignore=PT009

workflows:
  main:
    jobs:
      - integration_UNIX
      - unittest
