version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:

  integration_macos:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run:
          name: Install PostgresSQL

          environment:
            POSTGRES_USER: circleCI
            POSTGRES_DB: circleCI_test

          command: |
            brew install postgresql
  
  integration_linux:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install PostgresSQL
          command: |
            apt-get install postgresql


  unittest:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name : Run Unit Tests
          command: |
            python3 -m unittest tests/test_linting.py
            flake8 --max-line-length=120 --ignore=PT009

workflows:
  main:
    jobs:
      - integration_macos
      - integration_linux
      - unittest
