version: 2.1

orbs:
  python: circleci/python@0.2.1
  win: circleci/windows@2.2.0

jobs:
  unittest:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt
      - run:
          name : Run Unit Tests
          command: |
            flake8 --max-line-length=120 --ignore=PT009

  #UNIX integration 
  integration-on-UNIX:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python dependencies and postgresql installation
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo apt install -y postgresql-client || true
            sudo apt install postgresql

      - run:
          name: Integrate IsaTAB.sql into the database
          command: |
            service postgresql Isatab_DB
            psql -f AutoFlow-OmicsDataHandling/IsaTab.sql Isatab_DB

  #Windows integration
  Integration-on-windows:
    executor:
      name: win/default
      shell: powershell.exe

    steps:
      - checkout
      - run:
          name: Install postgresql
          command : |
            choco install postgresql
            python -m pip install -U pip

      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt

      - run:
          name : Integrate IsaTAB.sql into the database
          command: |
            psql -h localhost -U biosustain -d biosustaindb -f AutoFlow-OmicsDataHandling/IsaTab.sql


workflows:
  main:
    jobs:
      - integration-on-UNIX
      - unittest