version: 2.1

orbs:
  python: circleci/python@0.2.1
  win: circleci/windows@2.2.0

jobs:
  #Linting and unit test
  unittest:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name : Run Unit Tests
          command: |
            python3 -m unittest tests/test_linting.py
            flake8 --max-line-length=120 --ignore=PT009

  #UNIX integration 
  Integration-on-UNIX:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python dependencies and postgresql installation
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo apt install -y postgresql-client || true
            sudo apt install postgresql

      - run:
          name: Integrate IsaTAB.sql into the database
          command: |
            psql -c "create database Isatab_DB" -U postgres -h localhost -p 5432
            psql -f AutoFlow-OmicsDataHandling/IsaTab.sql Isatab_DB

  #Windows integration
  Integration-on-windows:
    executor:
      name: win/default
      shell: powershell.exe

    steps:
      - checkout
      - run:
          name: Install postgresql
          command : |
            choco install postgresql
            python -m pip install -U pip

      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt

      - run:
          name : Integrate IsaTAB.sql into the database
          command: |
            psql -c "create database Isatab_DB" -U postgres -h localhost -p 5432
            psql -h localhost -U biosustain -d biosustaindb -f AutoFlow-OmicsDataHandling/IsaTab.sql
              
  #MacOS integration
  Integration-on-macos:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run:
          name: Install PostgresSQL

          environment:
            POSTGRES_USER: circleCI
            POSTGRES_DB: circleCI_test

          command: |
            brew install postgresql

      - run:
          name: Integrate IsaTAB.sql into the database
          command: |
            psql -c "create database Isatab_DB" -U postgres -h localhost -p 5432
            psql -f AutoFlow-OmicsDataHandling/IsaTab.sql Isatab_DB

workflows:
  main:
    jobs:
      - unittest
      - Integration-on-UNIX
      - Integration-on-windows
      - Integration-on-macos