version: 2.1

orbs:
  win: circleci/windows@2.4.0

commands:
  install-conda:
    steps:
      - run:
          name: Installing Miniconda
          command: |
            MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
            curl -sSL -O "https://repo.continuum.io/miniconda/${MINICONDA_FILE}"
            bash "${MINICONDA_FILE}" -b -p ~/miniconda3
            rm -rf "${MINICONDA_FILE}"
            eval "$(~/miniconda3/bin/conda shell.bash hook)"
            conda init
  setup-env:
    parameters:
      os:
        type: enum
        default: "linux"
        enum: ["linux", "win"]
    steps:
      - restore_cache:
          key: conda-{{ arch }}-{{ checksum "env.yml" }}
      - when:
          condition:
            equal: [ "linux", << parameters.os >> ]
          steps:
            - run:
                name: Installing libXrender
                command: |
                  sudo apt-get update
                  sudo apt-get install libxrender1
            - run: 
                name: Setting up environment
                command: |
                  eval "$(~/miniconda3/bin/conda shell.bash hook)"
                  conda env create -f env.yml
      - when:
          condition:
            equal: [ "win", << parameters.os >> ]
          steps:
            - run:
                name: Setting up environment
                command: |
                  conda init powershell
                  conda env create -f env.yml
      - save_cache:
          key: conda-{{ arch }}-{{ checksum "env.yml" }}
          paths:
            - ~/miniconda
  test:
    parameters:
      os:
        type: enum
        default: "linux"
        enum: ["linux", "win"]
    steps:
      - when:
          condition:
            equal: [ "linux", << parameters.os >> ]
          steps:
            - run:
                name: Running tests
                command: |
                  eval "$(~/miniconda3/bin/conda shell.bash hook)"
                  conda activate test
                  python -m pytest --disable-warnings
                  python -m flake8 --max-line-length=120 --ignore=PT009,E203,W503,W601
      - when:
          condition:
            equal: [ "win", << parameters.os >> ]
          steps:
            - run: 
                name: Running tests
                command: |
                  Set-StrictMode -Version Latest
                  $ErrorActionPreference = 'Stop'
                  function ThrowOnFailure($Msg) { if (-not $?) { throw $Msg } }
                  conda activate test
                  python -m pytest --disable-warnings
                  ThrowOnFailure "Python test failed!"
                  python -m flake8 --max-line-length=120 --ignore=PT009,E203,W503,W601

jobs:
  unittest:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - install-conda
      - setup-env
      - test
  win-unittest:
    executor: win/default
    steps:
      - checkout
      - setup-env:
          os: win
      - test:
          os: win

  # Linux integration
  Integration-on-linux:
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:13.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Install Python dependencies and postgresql installation
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo apt install -y postgresql-client || true
            sudo apt install postgresql

      - run:
          name: Integrate BFAIR.sql into the database
          command: |
            psql -h localhost -p 5432 -U postgres -c "create database test_db"
            psql -h localhost -p 5432 -U postgres -f Back-Frontend/backend/BFAIR_latest.sql test_db

  # Windows integration
  Integration-on-windows:
    executor:
      name: win/default
      shell: powershell.exe

    steps:
      - checkout
      - run:
          name: Install postgresql
          command : |
            choco install postgresql13 --params "/Password:$Env:WIN_PGPASSWORD"
            python -m pip install -U pip

      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt --ignore-installed ruamel.yaml

      - run:
          name : Integrate BFAIR.sql into the database
          no_output_timeout: 30m
          command: |
            $Env:PGPASSWORD="$Env:WIN_PGPASSWORD"
            C:\"Program Files"\PostgreSQL\13\bin\psql.exe -U postgres -h localhost -p 5432 -d postgres -v ON_ERROR_STOP=1 -c "create database BFAIR_DB"
            C:\"Program Files"\PostgreSQL\13\bin\psql.exe -U postgres -h localhost -p 5432 -v ON_ERROR_STOP=1 -f Back-Frontend/backend/BFAIR_latest.sql

  # MacOS integration
  Integration-on-macos:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run:
          name: Install PostgresSQL
          command: |
            brew install postgresql
            brew services start postgresql

      - run:
          name: Integrate BFAIR.sql into the database
          environment:
            PAGER: cat
          command: |
            psql -q -c "create database BFAIR_DB" -d postgres
            psql -b -q -v ON_ERROR_STOP=1 -f Back-Frontend/backend/BFAIR_latest.sql -d postgres

workflows:

  version: 2
  main:
    jobs:
      - unittest
      - win-unittest
      - Integration-on-linux
      - Integration-on-macos:
          filters:
            branches:
              only:
                - develop
                - master
                - /release-.*/
      - Integration-on-linux:
          filters:
            branches:
              only:
                - develop
                - master
                - /release-.*/
      - Integration-on-windows:
          filters:
              branches:
                only:
                  - develop
                  - master
                  - /release-.*/