version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  
  build-in-python:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command : |
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name : Run Unit Tests
          command: |
            python3 -m pytest tests

workflows:
  main:
    jobs:
      - build-in-python