"""empty message

Revision ID: 5f840c5a7ac9
Revises: 063465cdd3ae
Create Date: 2021-02-24 12:08:53.697067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f840c5a7ac9'
down_revision = '063465cdd3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Methodology_Sample_id_fkey', 'Methodology', type_='foreignkey')
    op.create_foreign_key(None, 'Methodology', 'Sample', ['Sample_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Methodology', type_='foreignkey')
    op.create_foreign_key('Methodology_Sample_id_fkey', 'Methodology', 'Sample', ['Sample_id'], ['id'])
    # ### end Alembic commands ###
